import type { FeatureFlow } from "../../shared/types";

export const MOCK_FLOWS: FeatureFlow[] = [
  // --- Attention-needing flows first (shown prominently) ---
  {
    id: "flow-1",
    title: "feat: parallel agent orchestration for review",
    branch: "feat/agent-orchestration",
    headSha: "abc1234",
    repo: "acme/platform",
    updatedAt: new Date(Date.now() - 5 * 60000).toISOString(),
    needsAttention: [
      {
        reason: "check_failed",
        stage: "checks",
        url: "https://github.com/acme/platform/actions/runs/12345",
      },
    ],
    stages: [
      {
        id: "work",
        state: "done",
        summary: "authored",
        url: "https://github.com/acme/platform/pulls",
        satellites: [
          {
            id: "agent-1",
            kind: "agent",
            label: "Copilot Agent",
            focus: "implementing parallel review orchestration",
            status: "passed",
            url: "https://github.com/acme/platform/pulls/42",
          },
        ],
      },
      {
        id: "pr",
        state: "done",
        summary: "#42",
        url: "https://github.com/acme/platform/pull/42",
        satellites: [],
      },
      {
        id: "checks",
        state: "failed",
        summary: "2/3",
        logUrl: "https://github.com/acme/platform/actions/runs/12345",
        satellites: [],
      },
      { id: "review", state: "pending", satellites: [] },
      { id: "merge", state: "pending", satellites: [] },
      { id: "deploy", state: "pending", satellites: [] },
      { id: "prod", state: "pending", satellites: [] },
    ],
  },
  {
    id: "flow-3",
    title: "chore: upgrade dependencies to latest",
    branch: "chore/dep-upgrade",
    repo: "acme/platform",
    updatedAt: new Date(Date.now() - 2 * 60 * 60000).toISOString(),
    needsAttention: [
      {
        reason: "review_requested",
        stage: "review",
        url: "https://github.com/acme/platform/pull/40",
      },
    ],
    stages: [
      {
        id: "work",
        state: "done",
        summary: "authored",
        satellites: [],
      },
      {
        id: "pr",
        state: "done",
        summary: "#40",
        url: "https://github.com/acme/platform/pull/40",
        satellites: [],
      },
      {
        id: "checks",
        state: "done",
        summary: "4/4",
        satellites: [],
      },
      {
        id: "review",
        state: "active",
        summary: "you",
        url: "https://github.com/acme/platform/pull/40",
        satellites: [
          {
            id: "ai-review-3",
            kind: "ai_review",
            label: "Copilot Review",
            status: "waiting",
            url: "https://github.com/acme/platform/pull/40#pullrequestreview-3",
          },
        ],
      },
      { id: "merge", state: "pending", satellites: [] },
      { id: "deploy", state: "pending", satellites: [] },
      { id: "prod", state: "pending", satellites: [] },
    ],
  },
  {
    id: "flow-4",
    title: "feat: dark mode theming system",
    branch: "feat/dark-mode",
    repo: "acme/platform",
    updatedAt: new Date(Date.now() - 4 * 60 * 60000).toISOString(),
    needsAttention: [
      {
        reason: "deploy_waiting_approval",
        stage: "deploy",
        url: "https://github.com/acme/platform/deployments/staging",
      },
    ],
    stages: [
      {
        id: "work",
        state: "done",
        summary: "authored",
        satellites: [
          {
            id: "agent-4",
            kind: "agent",
            label: "Copilot Agent",
            focus: "building CSS variable system",
            status: "passed",
            url: "https://github.com/acme/platform/pull/39",
          },
          {
            id: "sub-4a",
            kind: "subagent",
            label: "Component Scanner",
            focus: "enumerating components to theme",
            status: "passed",
            parentId: "agent-4",
            url: "https://github.com/acme/platform/pull/39",
          },
        ],
      },
      {
        id: "pr",
        state: "done",
        summary: "#39",
        url: "https://github.com/acme/platform/pull/39",
        satellites: [],
      },
      {
        id: "checks",
        state: "done",
        summary: "5/5",
        satellites: [],
      },
      {
        id: "review",
        state: "done",
        summary: "approved",
        satellites: [],
      },
      {
        id: "merge",
        state: "done",
        summary: "merged",
        satellites: [],
      },
      {
        id: "deploy",
        state: "active",
        summary: "waiting",
        satellites: [
          {
            id: "env-staging-4",
            kind: "environment",
            label: "staging",
            status: "waiting",
            url: "https://github.com/acme/platform/deployments/staging",
          },
        ],
      },
      { id: "prod", state: "pending", satellites: [] },
    ],
  },
  {
    id: "flow-5",
    title: "fix: memory leak in event listener cleanup",
    branch: "fix/event-listener-leak",
    headSha: "abc9999",
    mergeCommitSha: "def8888",
    repo: "acme/platform",
    updatedAt: new Date(Date.now() - 6 * 60 * 60000).toISOString(),
    needsAttention: [
      {
        reason: "deploy_failed",
        stage: "deploy",
        url: "https://github.com/acme/platform/deployments/activity_log",
      },
    ],
    stages: [
      { id: "work", state: "done", summary: "authored", satellites: [] },
      { id: "pr", state: "done", summary: "#38", url: "https://github.com/acme/platform/pull/38", satellites: [] },
      { id: "checks", state: "done", summary: "3/3", satellites: [] },
      { id: "review", state: "done", summary: "approved", satellites: [] },
      { id: "merge", state: "done", summary: "merged", satellites: [] },
      {
        id: "deploy",
        state: "failed",
        summary: "failed",
        logUrl: "https://github.com/acme/platform/deployments/activity_log",
        satellites: [
          {
            id: "env-staging-5",
            kind: "environment",
            label: "staging",
            status: "failed",
            url: "https://github.com/acme/platform/deployments/activity_log",
          },
        ],
      },
      { id: "prod", state: "pending", satellites: [] },
    ],
  },
  {
    id: "flow-7",
    title: "feat: settings panel redesign",
    branch: "feat/settings-panel-redesign",
    headSha: "cde2345",
    repo: "acme/platform",
    updatedAt: new Date(Date.now() - 90 * 60000).toISOString(),
    needsAttention: [
      {
        reason: "changes_requested",
        stage: "review",
        url: "https://github.com/acme/platform/pull/43",
      },
    ],
    stages: [
      {
        id: "work",
        state: "done",
        summary: "authored",
        url: "https://github.com/acme/platform/pull/43",
        satellites: [
          {
            id: "agent-7",
            kind: "agent",
            label: "Copilot Agent",
            focus: "redesigning settings panel layout",
            status: "passed",
            url: "https://github.com/acme/platform/pull/43",
          },
          {
            id: "sub-7a",
            kind: "subagent",
            label: "Type Checker",
            focus: "type-checking pass",
            status: "failed",
            parentId: "agent-7",
            url: "https://github.com/acme/platform/pull/43",
          },
        ],
      },
      {
        id: "pr",
        state: "done",
        summary: "#43",
        url: "https://github.com/acme/platform/pull/43",
        satellites: [],
      },
      {
        id: "checks",
        state: "done",
        summary: "3/3",
        satellites: [],
      },
      {
        id: "review",
        state: "failed",
        summary: "changes",
        url: "https://github.com/acme/platform/pull/43",
        satellites: [],
      },
      { id: "merge", state: "pending", satellites: [] },
      { id: "deploy", state: "pending", satellites: [] },
      { id: "prod", state: "pending", satellites: [] },
    ],
  },
  {
    id: "flow-8",
    title: "refactor: extract shared auth utilities",
    branch: "refactor/shared-auth-utils",
    headSha: "fgh3456",
    repo: "acme/platform",
    updatedAt: new Date(Date.now() - 3 * 60 * 60000).toISOString(),
    needsAttention: [
      {
        reason: "merge_conflict",
        stage: "merge",
        url: "https://github.com/acme/platform/pull/44",
      },
    ],
    stages: [
      {
        id: "work",
        state: "done",
        summary: "authored",
        url: "https://github.com/acme/platform/pull/44",
        satellites: [],
      },
      {
        id: "pr",
        state: "done",
        summary: "#44",
        url: "https://github.com/acme/platform/pull/44",
        satellites: [],
      },
      {
        id: "checks",
        state: "done",
        summary: "4/4",
        satellites: [],
      },
      {
        id: "review",
        state: "done",
        summary: "approved",
        satellites: [],
      },
      {
        id: "merge",
        state: "failed",
        summary: "conflict",
        url: "https://github.com/acme/platform/pull/44",
        satellites: [],
      },
      { id: "deploy", state: "pending", satellites: [] },
      { id: "prod", state: "pending", satellites: [] },
    ],
  },
  // --- Calm flows (no attention, placed last so dimming contrast is clear) ---
  {
    id: "flow-2",
    title: "fix: resolve race condition in token refresh",
    branch: "fix/token-refresh-race",
    headSha: "def5678",
    mergeCommitSha: "ghi9012",
    repo: "acme/platform",
    updatedAt: new Date(Date.now() - 30 * 60000).toISOString(),
    needsAttention: [],
    stages: [
      {
        id: "work",
        state: "done",
        summary: "authored",
        url: "https://github.com/acme/platform/pulls",
        satellites: [
          {
            id: "agent-2",
            kind: "agent",
            label: "Copilot Agent",
            focus: "fixed race condition with mutex guard",
            status: "passed",
            url: "https://github.com/acme/platform/pull/41",
          },
        ],
      },
      {
        id: "pr",
        state: "done",
        summary: "#41",
        url: "https://github.com/acme/platform/pull/41",
        satellites: [],
      },
      {
        id: "checks",
        state: "done",
        summary: "3/3",
        satellites: [],
      },
      {
        id: "review",
        state: "done",
        summary: "approved",
        url: "https://github.com/acme/platform/pull/41",
        satellites: [
          {
            id: "ai-review-2",
            kind: "ai_review",
            label: "Copilot Review",
            status: "passed",
            url: "https://github.com/acme/platform/pull/41#pullrequestreview-2",
          },
        ],
      },
      {
        id: "merge",
        state: "done",
        summary: "merged",
        url: "https://github.com/acme/platform/pull/41",
        satellites: [],
      },
      {
        id: "deploy",
        state: "done",
        summary: "success",
        url: "https://github.com/acme/platform/deployments/staging",
        satellites: [
          {
            id: "env-staging",
            kind: "environment",
            label: "staging",
            status: "passed",
            url: "https://github.com/acme/platform/deployments/staging",
          },
        ],
      },
      {
        id: "prod",
        state: "done",
        summary: "live",
        url: "https://github.com/acme/platform/deployments/production",
        satellites: [
          {
            id: "env-prod",
            kind: "environment",
            label: "prod",
            status: "passed",
            url: "https://github.com/acme/platform/deployments/production",
          },
        ],
      },
    ],
  },
  {
    id: "flow-6",
    title: "feat: AI-powered code review suggestions",
    branch: "feat/ai-review-suggestions",
    repo: "acme/platform",
    updatedAt: new Date(Date.now() - 8 * 60 * 60000).toISOString(),
    needsAttention: [],
    stages: [
      {
        id: "work",
        state: "active",
        summary: "coding",
        satellites: [
          {
            id: "agent-6",
            kind: "agent",
            label: "Copilot Agent",
            focus: "implementing review suggestion engine",
            status: "running",
            url: "https://github.com/acme/platform/pulls",
          },
          {
            id: "sub-6a",
            kind: "subagent",
            label: "AST Parser",
            focus: "extracting code structure",
            status: "running",
            parentId: "agent-6",
            url: "https://github.com/acme/platform/pulls",
          },
        ],
      },
      { id: "pr", state: "no_data", satellites: [] },
      { id: "checks", state: "no_data", satellites: [] },
      { id: "review", state: "no_data", satellites: [] },
      { id: "merge", state: "no_data", satellites: [] },
      { id: "deploy", state: "no_data", satellites: [] },
      { id: "prod", state: "no_data", satellites: [] },
    ],
  },
];
